### ISSUE TITLE
How to flush all cache?

### ISSUE THREAD

**Issue by vukhanhtruong** [emgag/varnish-towncrier#2]
Hello,

I'm using Edge Side Includes (ESI) to boost my application's performance by storing fragments of server-side rendered pages in edge cache servers. Find out more [here](https://github.com/dunglas/react-esi).
I want to flush all caches after the code was deployed.
So, I've created a new method in `default.vcl` to flush all of the caches, see below.
However, the agent does not recognize the new one.
Can you give me your advice about how to flush them all?

```vcl
sub vcl_recv {
      if (req.method == "XCGFULLBAN") {
        if (!client.ip ~ purgers) {
          return(synth(405,"Not allowed."));
        }

        ban("req.http.host ~ .*");
        return (synth(200, "Full cache cleared"));
      }
  ....
}
```

Thank you very much for your great work. Keep your work up.
Regards,

**Comment by vukhanhtruong** [comment]
Oh sorry, my bad. I've not read your documentation carefully. I made it work. 

```sh
publish varnish.purge '{"command": "ban", "host": "mydomain", "value": ["req.http.host ~ .*"]}'
```

Thank you.

**Comment by maetthu** [comment]
Thank you, glad my tool is helpful :slightly_smiling_face: 

Be aware that although directly referencing request parameters (`req.*`) in ban expressions work, it does come with a cost. Bans are periodically cleaned up by varnish internally (called the "ban lurker"), so they don't need to be processed for each incoming request again and again. However, since request parameters are only available in a request and are not stored in the cached object, bans containing a `req.*` parameter cannot be cleaned up in the background and can pile up after a while - they can only be cleaned up if they are older than the oldest object in the cache. See https://varnish-cache.org/docs/6.3/users-guide/purging.html

What I usually do to mitigate this is to add certain request parameters to the response object, like

```
sub vcl_backend_response {
    [...]

    # be friendly to ban lurker
    set beresp.http.x-url = bereq.url;
    set beresp.http.x-host = bereq.http.host;

    [...]
}

sub vcl_deliver {
    [...]
    
    # remove some variables we used before
    unset resp.http.x-url;
    unset resp.http.x-host;
    [...]
}
```

and then reference those in the ban expression. To purge the complete cache, the ban expression would look like this: `obj.http.x-url ~ .`

**Comment by vukhanhtruong** [comment]
@maetthu It's informative. Thanks for your kindly support.

**Comment by vukhanhtruong** [comment]
Can I ask you a question? 
I'm using Kubernetes, I created the manifest that treat your containers as a proxy to the frontend app. It works efficiently so far. However, I think it could be better if it's possible to synchronize the cache data between the Varnish, isn't it?  What do you think?

Thank you.

**Comment by vukhanhtruong** [comment]
By the way, your [Varnish](https://github.com/emgag/docker-varnish) container (v6.3.2), its size is 423MB. It's pretty big. It would be nice if its size smaller. Thanks.

**Comment by maetthu** [comment]
@vukhanhtruong To synchronize/centralize caches, you'll need Varnish Enterprise, the community edition does not support that (there are some ugly workarounds/hacks like chaining varnish instances or instances having each other as a primary backend to have some sort of a shared cache, but that's really not something you should do). 

Regarding image size: This is mainly because varnish requires gcc to be installed, since VCL are converted to c and then compiled into shared objects... and gcc itself is big and comes with a lot of dependencies. Pretty sure you can shave off a couple of MB here and there, but it's not worth the effort IMHO, pull requests are welcome though.
